PMI/ProjectAdmin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pmi/' , include('pmi.urls', namespace="pmi")),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/login'}),
    #url(r'^Editar_proyecto/informacion_tareas/agregar_tarea/$', crearTarea),
    #url(r'^proyectos/$', proyectos),
    #url(r'^Editar_proyecto/informacion_proyecto/$', informacionDeProyecto),
    #url(r'^crear_proyecto/$', crearProyecto),
    #url(r'^Editar_proyecto/informacion_tareas/$', informeTareas),
    #url(r'^Editar_proyecto/$', editarProyecto),
)

PMI/pmi/urls.py
from django.conf.urls import patterns, url

from pmi import views

urlpatterns = patterns('',
    url(r'^editar_proyecto/informacion_proyecto/editar_informacion_proyecto/$', views.editarInformacionProyecto, name="editarInformacionProyecto"),
    url(r'^editar_proyecto/informacion_tareas/agregar_tarea/$', views.crearTarea, name="crearTarea"),
    url(r'^proyectos/$', views.proyectos, name="proyectos"),
    url(r'^editar_proyecto/informacion_proyecto/$', views.informacionDeProyecto, name="informacionDeProyecto"),
    url(r'^crear_proyecto/$', views.crearProyecto, name="crearProyecto"),
    url(r'^editar_proyecto/informacion_tareas/$', views.informeTareas, name="informeTareas"),
    url(r'^editar_proyecto/$', views.editarProyecto, name="editarProyecto"),
    url(r'^guardar_proyecto/$', views.guardarProyecto, name="guardarProyecto"),
    url(r'^guardar_tarea/$', views.guardarTarea, name="guardarTarea"),
    url(r'^informe_tareas/$', views.printInformeTareas, name="printInformeTareas"),
    
   
    
    


    
)

PMI/pmi/models.py
from django.db import models
from django import forms


class Proyecto(models.Model):
    nombre = models.CharField(max_length=100)
    comienzo_pro = models.DateTimeField()
    final_pro= models.DateTimeField()
    descripcion= models.CharField(max_length=300)
    def __str__(self):  
        return self.nombre
        
class Tarea(models.Model):
    nombre= models.CharField(max_length=100)
    comienzo= models.DateTimeField('Fecha de inicio')
    final= models.DateTimeField('Fecha final')
    proyecto= models.ForeignKey(Proyecto)
    def __str__(self):  
        return self.nombre

# Create your models here.

PMI/pmi/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse,  HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required

import datetime
from pmi.models import *
import time



def crearTarea(request):
    proyecto_lista= Proyecto.objects.all()
    return render(request, 'agregarTarea.html', {'proyecto_lista': proyecto_lista})

def guardarTarea(request):
    proyecto = get_object_or_404(Proyecto, pk=request.POST['proyecto'])
    proyecto.tarea_set.create(nombre=request.POST["nombre"], comienzo=request.POST["comienzo"], final=request.POST["final"])
    return HttpResponseRedirect(reverse('pmi:informeTareas'))


def proyectos(request):
    proyecto_lista = Proyecto.objects.all()
    return render(request, 'proyectos.html', {'proyecto_lista': proyecto_lista})

def informacionDeProyecto(request):
    proyecto_lista = Proyecto.objects.all()
    
    return render(request, 'Informacion_de_proyecto.html', {'proyecto_lista': proyecto_lista})
    
def editarInformacionProyecto(request):
    proyecto_lista = Proyecto.objects.all()
    if request.POST.get("ver"):	
    	proyecto = get_object_or_404(Proyecto, pk=request.POST['proyecto'])   
    	nombre=proyecto.nombre
    	descripcion= proyecto.descripcion
        comienzo = proyecto.comienzo_pro 
    	final = proyecto.final_pro
	return render(request,'Informacion_de_proyecto.html', {'proyecto_lista': proyecto_lista, "proyecto": proyecto } )
    if request.POST.get("eliminar"):
	proyecto_lista = Proyecto.objects.all()
	proyecto = get_object_or_404(Proyecto, pk=request.POST['proyecto'])
        proyecto.delete()
        return HttpResponseRedirect(reverse('pmi:proyectos'))
    if request.POST.get("guardar"):
	proyecto = get_object_or_404(Proyecto, pk=request.POST['proyecto'])
	proyecto.descripcion= request.POST.get("descripcion2")
	proyecto.comienzo_pro= request.POST.get("nueva_fecha1")
	proyecto.final_pro= request.POST.get("nueva_fecha2")
	
	proyecto.save()
	return HttpResponseRedirect(reverse('pmi:proyectos'))
	
    return render(request,'Informacion_de_proyecto.html', {'proyecto_lista': proyecto_lista } )

@permission_required('pmi.crearProyecto')

def crearProyecto(request):
    return render(request, 'crear_proyecto.html')

def guardarProyecto(request):
    proyecto = Proyecto(nombre=request.POST["nombre"],comienzo_pro=request.POST["comienzo_pro"], final_pro=request.POST["final_pro"], descripcion=request.POST["descripcion"])  
    proyecto.save()
    return HttpResponseRedirect(reverse('pmi:proyectos'))



def informeTareas(request):
    proyecto_lista = Proyecto.objects.all()
    tareas_lista = Tarea.objects.all() 
    
	
    return render(request, 'informacionDeTareas.html',  {'proyecto_lista': proyecto_lista,"tareas_lista": tareas_lista })
  
def eliminarTarea(request):
    proyecto = get_object_or_404(Proyecto, pk=request.POST['proyecto']) 
    proyecto_lista = Proyecto.objects.all()
    tareas_lista = Tarea.objects.filter(proyecto=proyecto)
    return render(request,'informacionDeTareas.html', {'proyecto_lista': proyecto_lista, "tareas_lista": tareas_lista } )
    
def printInformeTareas(request):
    proyecto = get_object_or_404(Proyecto, pk=request.POST['proyecto']) 
    proyecto_lista = Proyecto.objects.all()
    tareas_lista = Tarea.objects.all()
    if request.POST.get("agregar"):
	return HttpResponseRedirect(reverse('pmi:crearTarea'))
    if request.POST.get("filtrar"):
        proyecto_lista = Proyecto.objects.all()
	tareas_lista = Tarea.objects.filter(proyecto=proyecto)
        return render(request,'informacionDeTareas.html', {'proyecto_lista': proyecto_lista, "tareas_lista": tareas_lista } )
    if request.POST.get("eliminar"):
	proyecto_lista = Proyecto.objects.all()
        tareas_lista = Tarea.objects.all()
	tareaid=request.POST.get("select_tarea")
        tarea= get_object_or_404(Tarea, pk= tareaid)
        tarea.delete()
	return render(request,'informacionDeTareas.html', {'proyecto_lista': proyecto_lista, "tareas_lista": tareas_lista } )
      
    return render(request,'informacionDeTareas.html', {'proyecto_lista': proyecto_lista, "tareas_lista": tareas_lista } )
@permission_required('pmi.editarProyecto')
def editarProyecto(request):
    return HttpResponseRedirect(reverse('pmi:informacionDeProyecto'))

PMI/pmi/templates/Informacion_de_proyecto.html
{% extends "general.html" %}



    {% block content %}

    
        <div class="container">
                     
            <div class="row">
                <div class="col-sm-3">
                    <div class="sidebar-nav">
                        <div class="navbar navbar-default" role="navigation">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <span class="visible-xs navbar-brand">Sidebar menu</span>
                            </div>
                            <div class="navbar-collapse collapse sidebar-navbar-collapse">
                            <ul class="nav navbar-nav">                                
                                <li ><a href="http://127.0.0.1:8000/pmi/editar_proyecto/informacion_proyecto/">informacion de proyectos</a></li>
                                <li><a href="http://127.0.0.1:8000/pmi/editar_proyecto/informacion_tareas/">informacion de tareas</a></li>                                                               
                            </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-offset-1 col-lg-6"> 
            
                    <form role="form" method= "post" action="{% url 'pmi:editarInformacionProyecto'%}" >
		    {% csrf_token %}
                        <div class="form-group">
                            <label for="proyecto">Seleccionar proyecto</label>
                            <div class="input-group">
                                    <div class="input-group-btn">
                                       <select id="proyecto" name="proyecto" class="form-control priority-value">
                                    {% for proyecto in proyecto_lista %}
                                        <option  value="{{proyecto.id}}">{{proyecto.nombre}}</option>
                                    {%endfor%}
                                    </select>
                                    </div>
                                </div>
                        </div>                        
                        <br></br>
                      
                            <div class="form-group">
                            <label for="ejemplo_proyecto_1">Descripcion del proyecto</label>
                            <input type="text" class="form-control" name="descripcion" id="ejemplo_proyecto_1" value="{{proyecto.descripcion}}">
			    </div>
                         <div class="form-group">
                            <label for="ejemplo_proyecto_1">Descripcion nueva</label>
                            <input type="text" class="form-control" name="descripcion2" id="ejemplo_proyecto_1" placeholder="describa el proyecto">
			    </div>   
                        <div class="form-group">
                            <label for="ejemplo_fechai_1">Fecha de inicio</label>
                            <input type="text" class="form-control" id="ejemplo_fechai_1"  value= "{{proyecto.comienzo_pro}}" >
                        </div>
			<div class="form-group">
                            <label for="ejemplo_fechai_1">Nueva fecha de inicio</label>
                            <input name="nueva_fecha1"type="date" class="form-control" id="ejemplo_fechai_1"  value= "{{proyecto.comienzo_pro}}" >
                        </div>
                        <div class="form-group">
                            <label for="ejemplo_fechaf_1">Fecha final</label>
                            <input type="text"  class="form-control" value="{{proyecto.final_pro}}" id="ejemplo_fechaf_1" >
                        </div>
			<div class="form-group">
                            <label for="ejemplo_fechaf_1">Nueva fecha final</label>
                            <input name="nueva_fecha2"type="date" value="{{final}}" class="form-control" value="{{proyecto.final_pro}}" id="ejemplo_fechaf_1" >
                        </div>
                        <br></br> 
			<input  type="submit" class="btn btn-default col-lg-3 col-offset-1" value="ver" name="ver" >         
                        <input  type="submit" class="btn btn-default col-lg-3 col-offset-1" value="gurdar" name="guardar" >
                        <input  type="submit" class="btn btn-default col-lg-3 col-offset-1" value="eliminar" name="eliminar" >
                    </form>
                </div>
  
            </div>
        </div>
    {% endblock %}

PMI/pmi/templates/agregarTarea.html
{% extends "general.html" %}

    {% block content %}

        <div class="container">
            
            
            <div class="row"> 
                <div class="col-lg-offset-3 col-lg-6"> 
            
                     <form action="{% url 'pmi:guardarTarea'%}"role="form" method= "post" >
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="nombre">Nombre de la tarea</label>
                            <input type="tarea" class="form-control" id="nombre" name="nombre" placeholder="Nombre tarea">
                        </div>
                        <div class="form-group">                        
                            <label for="proyecto">Proyecto al que pertenece</label>                           
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <select id="proyecto" name="proyecto" class="form-control priority-value">
                                    {% for proyecto in proyecto_lista %}
                                        <option value="{{proyecto.id}}">{{proyecto.nombre}}</option>
                                    {%endfor%}
                                    </select>
                                 </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="comienzo">Fecha de inicio</label>
                            <input type="date" class="form-control" id="comienzo" name="comienzo"  >
                        </div>
                        <div class="form-group">
                            <label for="final">Fecha final</label>
                            <input type="date" class="form-control" id="final" name="final" >
                        </div>

          
                        <button type="submit" class="btn btn-default col-lg-offset-5">Agregar</button>
                    </form>
                </div>
            </div>
        </div>
    {% endblock %}

PMI/pmi/templates/crear_proyecto.html
{% extends "general.html" %}



    {% block content %}
        <div class="container">           
           
            <div class="row"> 
                <div class="col-lg-offset-3 col-lg-6"> 
            
                    <form role="form" action="{% url 'pmi:guardarProyecto' %}" method="post">
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="nombre">Nombre del proyecto</label>
                            <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre proyecto">
                        </div>
                        <div class="form-group">
                            <label for="descripcion">Descripcion del proyecto</label>
                            <input type="text" class="form-control" id="descripcion"placeholder="descripcion del proyecto" name="descripcion">
                            
                        <div class="form-group">
                            <label for="comienzo_pro">Fecha de inicio</label>
                            <input type="date" class="form-control" id="comienzo_pro" name="comienzo_pro" >
                        </div>
                        <div class="form-group">
                            <label for="final_pro">Fecha final</label>
                            <input type="date" class="form-control" id="final_pro" name="final_pro" >
                        </div>

          
                        <button type="submit" class="btn btn-default col-lg-offset-5" value="guardar">Crear</button>
                    </form>
                </div>
            </div>
        </div>
    {% endblock %}

    

PMI/pmi/templates/editar_proyecto.html
{% extends "general.html" %}

    {% block content %}


        <div class="container">
            
            <div class="row">
                <div class="col-sm-3">
                    <div class="sidebar-nav">
                        <div class="navbar navbar-default" role="navigation">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <span class="visible-xs navbar-brand">Sidebar menu</span>
                            </div>
                            <div class="navbar-collapse collapse sidebar-navbar-collapse">
                            <ul class="nav navbar-nav">                                
                                <li><a href="http://127.0.0.1:8000/Editar_proyecto/informacion_proyecto">informacion de proyectos</a></li>
                                <li><a href="http://127.0.0.1:8000/Editar_proyecto/informacion_tareas/">informacion de tareas</a></li>                                                               
                            </ul>
                            </div><!--/.nav-collapse -->
                        </div>
                    </div>
                </div>
  
            </div>
        </div>
    {% endblock %}
   

PMI/pmi/templates/editpro.html
{% extends "general.html" %}



    {% block content %}
	
      proyecto
    
      
    {% endblock %}

PMI/pmi/templates/general.html
<!DOCTYPE html>
<html>
    <head>
        <title> PMI </title>
         <link rel="stylesheet" href="/static/boot/css/bootstrap.min.css">
         <link rel="stylesheet" href="/static/boot/css/example.css">
         <link rel="stylesheet" href="/static/boot/css/bootstrap-theme.min.css">
         <link rel="stylesheet" href="/static/boot/css/bootstrap.min.js">
    </head>
    <body>
        <div class="container">
	<div class="pull-right">

{{ user }}
{% if user.is_anonymous %}
<a href="{% url 'django.contrib.auth.views.login' %}">login</a>
{% else %}
<a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
{% endif %}
</div>	
            <div class="row">                
                <div class="masthead">
                  
                    <h3 class="text-muted"> PMI</h3>                    
                    
                    <ul class="nav nav-justified" >
                        <li class="col-md-4 col-lg-4 "><a href="http://127.0.0.1:8000/pmi/proyectos/" class="brand">Proyectos</a></li>
                        <li class=" col-md-5 col-lg-5"><a href="http://127.0.0.1:8000/pmi/crear_proyecto/" class="brand">Crear proyecto</a></li>
                        <li class="col-md-6 col-lg-6"><a href="http://127.0.0.1:8000/pmi/editar_proyecto/" class="brand">Editar proyecto</a></li>
                    </ul>

                </div>
            </div>
            <br> 
            </br>
            <br> 
            </br>
            <br> 
            </br>
            <div>
                 {% block content %}{% endblock %}
            </div>
            
        </div>
    </body>
</html>

PMI/pmi/templates/guardar.html
{% extends "general.html" %}



    {% block content %}
    <h1> proyecto creado </h1>
    {% endblock%}

PMI/pmi/templates/informacionDeTareas.html
{% extends "general.html" %}

    {% block content %}
        <div class="container">
                              
            <div class="row">
                <div class="col-sm-3">
                    <div class="sidebar-nav">
                        <div class="navbar navbar-default" role="navigation">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <span class="visible-xs navbar-brand">Sidebar menu</span>
                            </div>
                            <div class="navbar-collapse collapse sidebar-navbar-collapse">
                            <ul class="nav navbar-nav">                                
                                <li ><a href="http://127.0.0.1:8000/Editar_proyecto/informacion_proyecto">informacion de proyectos</a></li>
                                <li><a href="#">informacion de tareas</a></li>                                                               
                            </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-offset-1 col-lg-6"> 
            
                    <form role="form"  method= "post" action="{% url 'pmi:printInformeTareas'  %}">
		    {% csrf_token %}	
                        <div class="form-group">
                            <label for="ejemplo_proyecto_1">Seleccionar proyecto</label>
                            <div class="input-group">
                                    <div class="input-group-btn">
                                        <select id="select-proyecto" name="proyecto"class="form-control priority-value">
                                            {% for proyecto in proyecto_lista %}
                                        <option  value="{{proyecto.id}}">{{proyecto.nombre}}</option>
                                    {%endfor%}
                                        </select>
                                    </div>
                                </div>
                        </div>                        
                        <br></br>
                        <div >
            		<table class="table table-striped table-bordered">
           			<thead>
	            			<tr>
	     						<th>Tarea</th>
	     						<th>Fecha inicio</th>
	     						<th>Fecha final</th>
 							<th>Proyecto</th>
							<th></th>

	     					
	     							     						
	  						</tr>
 						</thead>
				{% for tarea in tareas_lista %}

            			<tr>
  							<td >{{tarea.nombre}}</td>
							<td >{{tarea.comienzo}}</td>
							<td >{{tarea.final}}</td>
							<td >{{tarea.proyecto}}</td>
							<td ><input type="checkbox" name="select_tarea" value="{{tarea.id}}"></td>
							
						</tr>
				{% endfor%}
						
            		</table>

            	</div>        
                        <input  type="submit" class="btn btn-default col-lg-3 col-offset-1" value="agregar tarea" name="agregar" >
<input type="submit" class="btn btn-default col-lg-3 col-offset-1" value="eliminar" name="eliminar">
<input type="submit" class="btn btn-default col-lg-3 col-offset-1" value="Filtrar" name="filtrar">	

                    </form>
                </div>
  
            </div>
        </div>
    {% endblock %}

PMI/pmi/templates/nuevousuario.html
{% extends 'general.html' %}
	{% block content%}
		<form id='formulario' method='POST' action=''>
		{% csrf_token %}
			<table>{{formulario}}</table>
			<p><input type='submit' value='Registrar'></p>
		</form>
	{% endblock %}

PMI/pmi/templates/proyectos.html
{% extends "general.html" %}

    {% block content %}
        <div class="container">
            
            <div class="row">
            	<div class="col-lg-8 col-lg-offset-2">
            		<table class="table table-striped table-bordered">
            			<thead>
	            			<tr>
	     						<th>Nombre</th>
	     						<th>Fecha inicio</th>
	     						<th>Fecha final</th>
	     						<th>Descripcion</th>
	     						
	  						</tr>
 						</thead>
	            		{% for proyecto in proyecto_lista %}
							<tr>			
								<td>{{proyecto.nombre}}</td>
								<td>{{proyecto.comienzo_pro}}</td>
								<td>{{proyecto.final_pro}}</td>
								<td>{{proyecto.descripcion}}</td>			
							</tr>
						{% endfor %}
            		</table>

            	</div>
            </div>
            
        </div>
  {% endblock %}